<?php
$id_func=$_GET['id_func'];
$id_per=$_GET['id_per'];
require("config.inc.php");
require("database.class.php");
require("functions.inc.php");
$db = new Database(DB_SERVER, DB_USER, DB_PASS, DB_DATABASE);
$db->connect();
//----------HABILITAR TABLA-------------
	$rsp1=$db->query("
	SELECT p9 FROM ".TABLE37." 
	WHERE id_func='$id_func'
	");
	$rsxp1=$db->fetch_array($rsp1);
	if($rsxp1[p9]==1)
	{
	header ("Location: exito.php");	
	}
//-----------------------------
$post_numero = count($_POST);
$con=($post_numero-1)/8;
/*while ($post = each($_POST))
{
echo $post[0] . " = " . $post[1];
}*/
if (isset($_POST[save]))
{
unset($_POST["save"]);
$on_off=0;

//echo $con;
$post_etiquetas = array_keys($_POST); // obtiene los nombres de las varibles
$post_valores= array_values($_POST);// obtiene los valores de las varibles
// crea las variables y les asigna el valor
for($i=0;$i<$post_numero-1;$i++){ 
//--------CONVIERTE MAYUSCULAS
if (stristr($post_etiquetas[$i], "date"))
{	//$post_valores[$i]="2000-10-10";
	$post_valores[$i]=cambia_dateN_to_dateMy_1($post_valores[$i]);
//	echo $post_valores[$i];
	}
		$post_valores[$i]=strtoupper($post_valores[$i]);
//		echo $post_valores[$i];
}
//----------------------------------
//id_old_mov id_func charge rea_chan num_res gral_dir unit area date_start date_end TABLE: old_mov
//GENERA CONSULTAS
$k=1;
$l=1;
$consulta1="";
$valores1="";
$i=0;
while ($i < $post_numero-1)
{
	if ($i%8==0)
	{
		//echo "posicion $i: ".$post_valores[$i]."<br />";
		$j=$i+1;
		$k=$i+2;
		$l=$i+3;
		$m=$i+4;
		$n=$i+5;
		$o=$i+6;
		$p=$i+7;
		$camp1=$post_valores[$i];
		$camp2=$post_valores[$j];
		$camp3=$post_valores[$k];
		$camp4=$post_valores[$l];
		$camp5=$post_valores[$m];
		$camp6=$post_valores[$n];
		$camp7=$post_valores[$o];
		$camp8=$post_valores[$p];
/*		echo "<br />";
		echo "insert into tablex () values ($camp1,$camp2,$camp3,$camp4,$camp5,$camp6,$camp7,$camp8)";
		echo "<br />";*/
//-----------------------------------

//id_old_mov id_func charge rea_chan num_res gral_dir unit area date_start date_end TABLE: old_mov
	$rs=$db->query("
	INSERT INTO ".TABLE19." 
	(id_per, charge, rea_chan, num_res, gral_dir, unit, area, date_start, date_end)
	VALUES 
	('$id_per','$camp1','$camp2','$camp3','$camp4','$camp5','$camp6','$camp7','$camp8')");
	 
	if(!$rs)
	{exit;
	}
//	echo "verdad";		
//-----------------------------------
	}	
	$i++;
}
	//-------------DESABILITAR TABLA------------
	$rs7=$db->query("
	UPDATE ".TABLE37." SET p9='$on_off'
	WHERE id_func='$id_func'
	");	
	//----------------------------------------
header ("Location: exito.php");	
//--------CONVIERTE MAYUSCULAS--------FIN
//		//GENERA CONSULTAS		
//
///*		$valores1.= "$post_valores[$i],";
//		if($k/8==1){
//		$consulta.$l="";
//		$valores.$l="";
//		$l++;
//		}
//		$k++;
//*/
//	}
////	
//	$valores1=implode(", ", $post_valores);
//	echo $valores1;
//	for($i=0;$i<$post_numero-1;$i++){ 
//	echo("<br>POST[".$post_etiquetas[$i]."]=".$post_valores[$i]); 
//	}
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="stylesheet" href="estilo.css" type="text/css" media="all">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="jquery-1.4.1.min.js"></script>
<!-- FECHA -->
	<link rel="stylesheet" type="text/css" media="screen" href="css/screen.css" />
    <link href="estilo.css" rel="stylesheet" type="text/css">
	<link href="data/css/style-ext.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="data/css/ui/admincp/jquery-ui-1.8.17.custom.css">
	<script src="data/js/jquery-1.7.1.min.js"></script>
    <!-- VALIDATE -->
    <script src="js/jquery.metadata.js" type="text/javascript"></script>
	<script src="js/jquery.validate.js" type="text/javascript"></script>
    <script type="text/javascript">
	$.metadata.setType("attr", "validate");
	$(document).ready(function() {
	$("#form1").validate();	
	});
</script>
    <!-- VALIDATE -->
    <script type="text/javascript">
	$(document).ready(function(){
    $.validator.addMethod(
    "myDateChecker",
    function(value, element) {
        // put your own logic here, this is just a (crappy) example
        return value.match(/^\d\d?\-\d\d?\-\d\d\d\d$/);
    },
    "Por favor ingrese una fecha válida."
);
    $("#myFormId").validate({
        rules: {
            date: "myDateChecker"
        }
    });
});
	
    </script>
        
    
	<script src="data/js/ui/jquery.ui.core.js"></script>
	<script src="data/js/ui/jquery.ui.widget.js"></script>
	<script src="data/js/ui/jquery.ui.datepicker.js"></script>
	<link rel="stylesheet" href="data/css/ui/demos.css" >

	<script>
	$(function() {
		$( ".datpick" ).datepicker({
			changeMonth: true,
			changeYear: true,
			showOn: "button",
			yearRange: '-100:+0',
			buttonImage: "data/images/calendar.gif",
			buttonImageOnly: true
		});
	});
</script>

<!-- ------- -->



<script type="text/javascript">
c=0;
function agregar() {
	c=c+1;
	$(".campos").append('<div class="email'+c+'" style = "display: inline-block; margin-left: auto; margin-right: auto; width: 1033px ;"><div id="cab">CARGO EN LA INSTITUCION (EMPEZAR POR EL ACTUAL):</div><div id="cab">MOTIVO DEL CAMBIO DEL CARGO:</div><div id="cab">NÚMERO DE RESOLUCIÓN O MEMO:</div><div id="cab">DIRECCIÓN GENERAL:</div><div id="cab"><input name="charge'+c+'" type="text" id="charge'+c+'" size="35" maxlength="64" class="required"/></div><div id="cab"><select name="rea_chan'+c+'" id="rea_chan'+c+'"><option value="PROMOCIÓN">PROMOCIÓN</option><option value="RETIRO">RETIRO</option><option value="ROTACIÓN">ROTACIÓN</option><option value="TRANFERENCIA">TRANFERENCIA</option><option value="RENUNCIA">RENUNCIA</option></select></div><div id="cab"><input name="num_res'+c+'" type="text" id="num_res'+c+'" size="30" maxlength="64" class="required"/></div><div id="cab"><select name="gral_dir'+c+'" id="gral_dir'+c+'" style="width:200px"><option value="ACCESO Y PERMANENCIA (INFRAESTRUCTURA)">ACCESO Y PERMANENCIA (INFRAESTRUCTURA)</option><option value="APACITACION Y EVALUACION DEL DESEMPEÑO">CAPACITACION Y EVALUACION DEL DESEMPEÑO</option><option value="COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION">COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION</option><option value="CORRESPONDENCIA DESPACHO">CORRESPONDENCIA DESPACHO</option><option value="CORRESPONDENCIA EXTERNO SALIENTE">CORRESPONDENCIA EXTERNO SALIENTE</option><option value="DESPACHO DE EDUCACION">DESPACHO DE EDUCACION</option><option value="DESPACHO MINISTRO MEMORANDO">DESPACHO MINISTRO MEMORANDO</option><option value="DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS">DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS</option><option value="DIRECCION GENERAL DE ASUNTOS JURIDICOS">DIRECCION GENERAL DE ASUNTOS JURIDICOS</option><option value="DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA">DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA</option><option value="DIRECCION GENERAL DE EDUCACION DE ADULTOS">DIRECCION GENERAL DE EDUCACION DE ADULTOS</option>		<option value="DIRECCION GENERAL DE EDUCACION ESPECIAL">DIRECCION GENERAL DE EDUCACION ESPECIAL</option><option value="DIRECCION GENERAL DE EDUCACION PRIMARIA">DIRECCION GENERAL DE EDUCACION PRIMARIA</option><option value="DIRECCION GENERAL DE EDUCACION SECUNDARIA">DIRECCION GENERAL DE EDUCACION SECUNDARIA</option><option value="DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA">DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA</option>		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA">DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA</option>		<option value="DIRECCION GENERAL DE FORMACION DE MAESTROS">DIRECCION GENERAL DE FORMACION DE MAESTROS</option><option value="DIRECCION GENERAL DE PLANIFICACION">DIRECCION GENERAL DE PLANIFICACION</option><option value="DIRECCION GENERAL DE POST ALFABETIZACION">DIRECCION GENERAL DE POST ALFABETIZACION</option><option value="DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION">DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION</option><option value="EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL">EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL</option><option value="EQUIPO BONO JUANCITO PINTO">EQUIPO BONO JUANCITO PINTO</option><option value="EQUIPO DE  AUDITORIA II">EQUIPO DE  AUDITORIA II</option><option value="EQUIPO DE ACREDITACION UNIVERSITARIA">EQUIPO DE ACREDITACION UNIVERSITARIA</option><option value="EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES">EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES</option><option value="EQUIPO DE ADMINISTRACION DE PLANILLAS">EQUIPO DE ADMINISTRACION DE PLANILLAS</option><option value="EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO">EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO</option><option value="EQUIPO DE AUDITORIA I">EQUIPO DE AUDITORIA I</option><option value="EQUIPO DE BIENESTAR SOCIAL">EQUIPO DE BIENESTAR SOCIAL</option><option value="EQUIPO DE CONTABILIDAD">EQUIPO DE CONTABILIDAD</option><option value="EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS">EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS</option><option value="EQUIPO DE DESARROLLO ORGANIZACIONAL">EQUIPO DE DESARROLLO ORGANIZACIONAL</option><option value="EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS">EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS</option><option value="EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS">EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS</option><option value="EQUIPO DE EDUCACION ESPECIAL ">EQUIPO DE EDUCACION ESPECIAL </option><option value="EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA">EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA</option><option value="EQUIPO DE FORMACION ARTISTICA">EQUIPO DE FORMACION ARTISTICA</option><option value="EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)">EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)</option><option value="EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL">EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL</option><option value="EQUIPO DE FORMACION INICIAL">EQUIPO DE FORMACION INICIAL</option><option value="EQUIPO DE GENERO GENERACIONAL Y SOCIAL">EQUIPO DE GENERO GENERACIONAL Y SOCIAL</option><option value="EQUIPO DE GESTION CURRICULAR">EQUIPO DE GESTION CURRICULAR</option><option value="EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL">EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL</option><option value="EQUIPO DE GESTION INSTITUCIONAL DGEA">EQUIPO DE GESTION INSTITUCIONAL DGEA</option><option value="EQUIPO DE GESTION INSTITUCIONAL SEP">EQUIPO DE GESTION INSTITUCIONAL SEP</option><option value="EQUIPO DE GESTION Y DESARROLLO CURRICULAR">EQUIPO DE GESTION Y DESARROLLO CURRICULAR</option><option value="EQUIPO DE INFORMACION EDUCATIVA">EQUIPO DE INFORMACION EDUCATIVA</option><option value="EQUIPO DE INFRAESTRUCTURA">EQUIPO DE INFRAESTRUCTURA</option><option value="EQUIPO DE MEMORIA INSTITUCIONAL">EQUIPO DE MEMORIA INSTITUCIONAL</option><option value="EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS">EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS</option><option value="EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO">EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO</option><option value="EQUIPO DE PRESUPUESTOS">EQUIPO DE PRESUPUESTOS</option><option value="EQUIPO DE RELACIONES INTERNACIONALES">EQUIPO DE RELACIONES INTERNACIONALES</option><option value="EQUIPO DE SISTEMAS Y PROCESO DE DATOS">EQUIPO DE SISTEMAS Y PROCESO DE DATOS</option><option value="EQUIPO DE TESORERIA">EQUIPO DE TESORERIA</option><option value="EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)">EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)</option><option value="EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE ">EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE </option><option value="EQUIPO GESTION CURRICULAR INICIAL">EQUIPO GESTION CURRICULAR INICIAL</option><option value="EQUIPO GESTION CURRICULAR PRIMARIA">EQUIPO GESTION CURRICULAR PRIMARIA</option><option value="EQUIPO REGISTRO DOCENTE ADMINISTRATIVO">EQUIPO REGISTRO DOCENTE ADMINISTRATIVO</option><option value="EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC">EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC</option><option value="FORMACION Y CAPACITACION">FORMACION Y CAPACITACION</option><option value="35" title="INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES">INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES</option><option value="JEFATURA DE GABINETE">JEFATURA DE GABINETE</option>		<option value="OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA">OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA</option><option value="PORTAL EDUCATIVO">PORTAL EDUCATIVO</option><option value="PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)">PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)</option><option value="REGISTRO Y CONTROL DE PERSONAL">REGISTRO Y CONTROL DE PERSONAL</option><option value="SOPORTE TECNICO A USUARIOS">SOPORTE TECNICO A USUARIOS</option><option value="TELECENTROS EDUCATIVOS COMUNITARIO">TELECENTROS EDUCATIVOS COMUNITARIO</option><option value="UNIDAD ADMINISTRATIVA">UNIDAD ADMINISTRATIVA</option><option value="UNIDAD DE ANALISIS JURIDICO">UNIDAD DE ANALISIS JURIDICO</option><option value="UNIDAD DE AUDITORIA INTERNA">UNIDAD DE AUDITORIA INTERNA</option><option value="UNIDAD DE COMUNICACION SOCIAL">UNIDAD DE COMUNICACION SOCIAL</option><option value="UNIDAD DE GESTION DE PERSONAL DEL SEP">UNIDAD DE GESTION DE PERSONAL DEL SEP</option><option value="UNIDAD DE GESTION JURIDICA">UNIDAD DE GESTION JURIDICA</option><option value="UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO">UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO</option><option value="UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL">UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL</option><option value="UNIDAD DE TITULOS PROFESIONALES">UNIDAD DE TITULOS PROFESIONALES</option><option value="UNIDAD DE TRANSPARENCIA">UNIDAD DE TRANSPARENCIA</option><option value="UNIDAD DE UNIVERSIDADES ">UNIDAD DE UNIVERSIDADES </option><option value="UNIDAD FINANCIERA">UNIDAD FINANCIERA</option><option value="VICEMINISTERIO DE CIENCIA Y TECNOLOGIA">VICEMINISTERIO DE CIENCIA Y TECNOLOGIA</option><option value="VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL">VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL</option><option value="VICEMINISTERIO DE EDUCACION REGULAR">VICEMINISTERIO DE EDUCACION REGULAR</option><option value="VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL">VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL</option></select></div><div id="cab">UNIDAD:</div><div id="cab">ÁREA:</div><div id="cab">DE FECHA:</div><div id="cab">A FECHA:</div><div id="cab"><select name="unit'+c+'" id="unit'+c+'" style="width:200px"><option value="ACCESO Y PERMANENCIA (INFRAESTRUCTURA)">ACCESO Y PERMANENCIA (INFRAESTRUCTURA)</option><option value="APACITACION Y EVALUACION DEL DESEMPEÑO">CAPACITACION Y EVALUACION DEL DESEMPEÑO</option><option value="COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION">COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION</option><option value="CORRESPONDENCIA DESPACHO">CORRESPONDENCIA DESPACHO</option><option value="CORRESPONDENCIA EXTERNO SALIENTE">CORRESPONDENCIA EXTERNO SALIENTE</option><option value="DESPACHO DE EDUCACION">DESPACHO DE EDUCACION</option><option value="DESPACHO MINISTRO MEMORANDO">DESPACHO MINISTRO MEMORANDO</option><option value="DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS">DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS</option><option value="DIRECCION GENERAL DE ASUNTOS JURIDICOS">DIRECCION GENERAL DE ASUNTOS JURIDICOS</option><option value="DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA">DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA</option><option value="DIRECCION GENERAL DE EDUCACION DE ADULTOS">DIRECCION GENERAL DE EDUCACION DE ADULTOS</option>		<option value="DIRECCION GENERAL DE EDUCACION ESPECIAL">DIRECCION GENERAL DE EDUCACION ESPECIAL</option><option value="DIRECCION GENERAL DE EDUCACION PRIMARIA">DIRECCION GENERAL DE EDUCACION PRIMARIA</option><option value="DIRECCION GENERAL DE EDUCACION SECUNDARIA">DIRECCION GENERAL DE EDUCACION SECUNDARIA</option><option value="DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA">DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA</option>		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA">DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA</option>		<option value="DIRECCION GENERAL DE FORMACION DE MAESTROS">DIRECCION GENERAL DE FORMACION DE MAESTROS</option><option value="DIRECCION GENERAL DE PLANIFICACION">DIRECCION GENERAL DE PLANIFICACION</option><option value="DIRECCION GENERAL DE POST ALFABETIZACION">DIRECCION GENERAL DE POST ALFABETIZACION</option><option value="DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION">DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION</option><option value="EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL">EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL</option><option value="EQUIPO BONO JUANCITO PINTO">EQUIPO BONO JUANCITO PINTO</option><option value="EQUIPO DE  AUDITORIA II">EQUIPO DE  AUDITORIA II</option><option value="EQUIPO DE ACREDITACION UNIVERSITARIA">EQUIPO DE ACREDITACION UNIVERSITARIA</option><option value="EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES">EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES</option><option value="EQUIPO DE ADMINISTRACION DE PLANILLAS">EQUIPO DE ADMINISTRACION DE PLANILLAS</option><option value="EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO">EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO</option><option value="EQUIPO DE AUDITORIA I">EQUIPO DE AUDITORIA I</option><option value="EQUIPO DE BIENESTAR SOCIAL">EQUIPO DE BIENESTAR SOCIAL</option><option value="EQUIPO DE CONTABILIDAD">EQUIPO DE CONTABILIDAD</option><option value="EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS">EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS</option><option value="EQUIPO DE DESARROLLO ORGANIZACIONAL">EQUIPO DE DESARROLLO ORGANIZACIONAL</option><option value="EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS">EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS</option><option value="EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS">EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS</option><option value="EQUIPO DE EDUCACION ESPECIAL ">EQUIPO DE EDUCACION ESPECIAL </option><option value="EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA">EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA</option><option value="EQUIPO DE FORMACION ARTISTICA">EQUIPO DE FORMACION ARTISTICA</option><option value="EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)">EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)</option><option value="EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL">EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL</option><option value="EQUIPO DE FORMACION INICIAL">EQUIPO DE FORMACION INICIAL</option><option value="EQUIPO DE GENERO GENERACIONAL Y SOCIAL">EQUIPO DE GENERO GENERACIONAL Y SOCIAL</option><option value="EQUIPO DE GESTION CURRICULAR">EQUIPO DE GESTION CURRICULAR</option><option value="EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL">EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL</option><option value="EQUIPO DE GESTION INSTITUCIONAL DGEA">EQUIPO DE GESTION INSTITUCIONAL DGEA</option><option value="EQUIPO DE GESTION INSTITUCIONAL SEP">EQUIPO DE GESTION INSTITUCIONAL SEP</option><option value="EQUIPO DE GESTION Y DESARROLLO CURRICULAR">EQUIPO DE GESTION Y DESARROLLO CURRICULAR</option><option value="EQUIPO DE INFORMACION EDUCATIVA">EQUIPO DE INFORMACION EDUCATIVA</option><option value="EQUIPO DE INFRAESTRUCTURA">EQUIPO DE INFRAESTRUCTURA</option><option value="EQUIPO DE MEMORIA INSTITUCIONAL">EQUIPO DE MEMORIA INSTITUCIONAL</option><option value="EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS">EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS</option><option value="EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO">EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO</option><option value="EQUIPO DE PRESUPUESTOS">EQUIPO DE PRESUPUESTOS</option><option value="EQUIPO DE RELACIONES INTERNACIONALES">EQUIPO DE RELACIONES INTERNACIONALES</option><option value="EQUIPO DE SISTEMAS Y PROCESO DE DATOS">EQUIPO DE SISTEMAS Y PROCESO DE DATOS</option><option value="EQUIPO DE TESORERIA">EQUIPO DE TESORERIA</option><option value="EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)">EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)</option><option value="EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE ">EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE </option><option value="EQUIPO GESTION CURRICULAR INICIAL">EQUIPO GESTION CURRICULAR INICIAL</option><option value="EQUIPO GESTION CURRICULAR PRIMARIA">EQUIPO GESTION CURRICULAR PRIMARIA</option><option value="EQUIPO REGISTRO DOCENTE ADMINISTRATIVO">EQUIPO REGISTRO DOCENTE ADMINISTRATIVO</option><option value="EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC">EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC</option><option value="FORMACION Y CAPACITACION">FORMACION Y CAPACITACION</option><option value="35" title="INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES">INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES</option><option value="JEFATURA DE GABINETE">JEFATURA DE GABINETE</option>		<option value="OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA">OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA</option><option value="PORTAL EDUCATIVO">PORTAL EDUCATIVO</option><option value="PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)">PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)</option><option value="REGISTRO Y CONTROL DE PERSONAL">REGISTRO Y CONTROL DE PERSONAL</option><option value="SOPORTE TECNICO A USUARIOS">SOPORTE TECNICO A USUARIOS</option><option value="TELECENTROS EDUCATIVOS COMUNITARIO">TELECENTROS EDUCATIVOS COMUNITARIO</option><option value="UNIDAD ADMINISTRATIVA">UNIDAD ADMINISTRATIVA</option><option value="UNIDAD DE ANALISIS JURIDICO">UNIDAD DE ANALISIS JURIDICO</option><option value="UNIDAD DE AUDITORIA INTERNA">UNIDAD DE AUDITORIA INTERNA</option><option value="UNIDAD DE COMUNICACION SOCIAL">UNIDAD DE COMUNICACION SOCIAL</option><option value="UNIDAD DE GESTION DE PERSONAL DEL SEP">UNIDAD DE GESTION DE PERSONAL DEL SEP</option><option value="UNIDAD DE GESTION JURIDICA">UNIDAD DE GESTION JURIDICA</option><option value="UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO">UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO</option><option value="UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL">UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL</option><option value="UNIDAD DE TITULOS PROFESIONALES">UNIDAD DE TITULOS PROFESIONALES</option><option value="UNIDAD DE TRANSPARENCIA">UNIDAD DE TRANSPARENCIA</option><option value="UNIDAD DE UNIVERSIDADES ">UNIDAD DE UNIVERSIDADES </option><option value="UNIDAD FINANCIERA">UNIDAD FINANCIERA</option><option value="VICEMINISTERIO DE CIENCIA Y TECNOLOGIA">VICEMINISTERIO DE CIENCIA Y TECNOLOGIA</option><option value="VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL">VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL</option><option value="VICEMINISTERIO DE EDUCACION REGULAR">VICEMINISTERIO DE EDUCACION REGULAR</option><option value="VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL">VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL</option></select></div><div id="cab"><select name="area'+c+'" id="area'+c+'" style="width:200px"><option value="ACCESO Y PERMANENCIA (INFRAESTRUCTURA)">ACCESO Y PERMANENCIA (INFRAESTRUCTURA)</option><option value="APACITACION Y EVALUACION DEL DESEMPEÑO">CAPACITACION Y EVALUACION DEL DESEMPEÑO</option><option value="COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION">COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION</option><option value="CORRESPONDENCIA DESPACHO">CORRESPONDENCIA DESPACHO</option><option value="CORRESPONDENCIA EXTERNO SALIENTE">CORRESPONDENCIA EXTERNO SALIENTE</option><option value="DESPACHO DE EDUCACION">DESPACHO DE EDUCACION</option><option value="DESPACHO MINISTRO MEMORANDO">DESPACHO MINISTRO MEMORANDO</option><option value="DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS">DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS</option><option value="DIRECCION GENERAL DE ASUNTOS JURIDICOS">DIRECCION GENERAL DE ASUNTOS JURIDICOS</option><option value="DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA">DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA</option><option value="DIRECCION GENERAL DE EDUCACION DE ADULTOS">DIRECCION GENERAL DE EDUCACION DE ADULTOS</option>		<option value="DIRECCION GENERAL DE EDUCACION ESPECIAL">DIRECCION GENERAL DE EDUCACION ESPECIAL</option><option value="DIRECCION GENERAL DE EDUCACION PRIMARIA">DIRECCION GENERAL DE EDUCACION PRIMARIA</option><option value="DIRECCION GENERAL DE EDUCACION SECUNDARIA">DIRECCION GENERAL DE EDUCACION SECUNDARIA</option><option value="DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA">DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA</option><option value="DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA">DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA</option><option value="DIRECCION GENERAL DE FORMACION DE MAESTROS">DIRECCION GENERAL DE FORMACION DE MAESTROS</option><option value="DIRECCION GENERAL DE PLANIFICACION">DIRECCION GENERAL DE PLANIFICACION</option><option value="DIRECCION GENERAL DE POST ALFABETIZACION">DIRECCION GENERAL DE POST ALFABETIZACION</option><option value="DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION">DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION</option><option value="EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL">EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL</option><option value="EQUIPO BONO JUANCITO PINTO">EQUIPO BONO JUANCITO PINTO</option><option value="EQUIPO DE  AUDITORIA II">EQUIPO DE  AUDITORIA II</option><option value="EQUIPO DE ACREDITACION UNIVERSITARIA">EQUIPO DE ACREDITACION UNIVERSITARIA</option><option value="EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES">EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES</option><option value="EQUIPO DE ADMINISTRACION DE PLANILLAS">EQUIPO DE ADMINISTRACION DE PLANILLAS</option><option value="EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO">EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO</option><option value="EQUIPO DE AUDITORIA I">EQUIPO DE AUDITORIA I</option><option value="EQUIPO DE BIENESTAR SOCIAL">EQUIPO DE BIENESTAR SOCIAL</option><option value="EQUIPO DE CONTABILIDAD">EQUIPO DE CONTABILIDAD</option><option value="EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS">EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS</option><option value="EQUIPO DE DESARROLLO ORGANIZACIONAL">EQUIPO DE DESARROLLO ORGANIZACIONAL</option><option value="EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS">EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS</option><option value="EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS">EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS</option><option value="EQUIPO DE EDUCACION ESPECIAL ">EQUIPO DE EDUCACION ESPECIAL </option><option value="EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA">EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA</option><option value="EQUIPO DE FORMACION ARTISTICA">EQUIPO DE FORMACION ARTISTICA</option><option value="EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)">EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)</option><option value="EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL">EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL</option><option value="EQUIPO DE FORMACION INICIAL">EQUIPO DE FORMACION INICIAL</option><option value="EQUIPO DE GENERO GENERACIONAL Y SOCIAL">EQUIPO DE GENERO GENERACIONAL Y SOCIAL</option><option value="EQUIPO DE GESTION CURRICULAR">EQUIPO DE GESTION CURRICULAR</option><option value="EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL">EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL</option><option value="EQUIPO DE GESTION INSTITUCIONAL DGEA">EQUIPO DE GESTION INSTITUCIONAL DGEA</option><option value="EQUIPO DE GESTION INSTITUCIONAL SEP">EQUIPO DE GESTION INSTITUCIONAL SEP</option><option value="EQUIPO DE GESTION Y DESARROLLO CURRICULAR">EQUIPO DE GESTION Y DESARROLLO CURRICULAR</option><option value="EQUIPO DE INFORMACION EDUCATIVA">EQUIPO DE INFORMACION EDUCATIVA</option><option value="EQUIPO DE INFRAESTRUCTURA">EQUIPO DE INFRAESTRUCTURA</option><option value="EQUIPO DE MEMORIA INSTITUCIONAL">EQUIPO DE MEMORIA INSTITUCIONAL</option><option value="EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS">EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS</option><option value="EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO">EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO</option><option value="EQUIPO DE PRESUPUESTOS">EQUIPO DE PRESUPUESTOS</option><option value="EQUIPO DE RELACIONES INTERNACIONALES">EQUIPO DE RELACIONES INTERNACIONALES</option><option value="EQUIPO DE SISTEMAS Y PROCESO DE DATOS">EQUIPO DE SISTEMAS Y PROCESO DE DATOS</option><option value="EQUIPO DE TESORERIA">EQUIPO DE TESORERIA</option><option value="EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)">EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)</option><option value="EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE ">EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE </option><option value="EQUIPO GESTION CURRICULAR INICIAL">EQUIPO GESTION CURRICULAR INICIAL</option><option value="EQUIPO GESTION CURRICULAR PRIMARIA">EQUIPO GESTION CURRICULAR PRIMARIA</option><option value="EQUIPO REGISTRO DOCENTE ADMINISTRATIVO">EQUIPO REGISTRO DOCENTE ADMINISTRATIVO</option><option value="EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC">EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC</option><option value="FORMACION Y CAPACITACION">FORMACION Y CAPACITACION</option><option value="35" title="INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES">INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES</option><option value="JEFATURA DE GABINETE">JEFATURA DE GABINETE</option>		<option value="OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA">OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA</option><option value="PORTAL EDUCATIVO">PORTAL EDUCATIVO</option><option value="PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)">PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)</option><option value="REGISTRO Y CONTROL DE PERSONAL">REGISTRO Y CONTROL DE PERSONAL</option><option value="SOPORTE TECNICO A USUARIOS">SOPORTE TECNICO A USUARIOS</option><option value="TELECENTROS EDUCATIVOS COMUNITARIO">TELECENTROS EDUCATIVOS COMUNITARIO</option><option value="UNIDAD ADMINISTRATIVA">UNIDAD ADMINISTRATIVA</option><option value="UNIDAD DE ANALISIS JURIDICO">UNIDAD DE ANALISIS JURIDICO</option><option value="UNIDAD DE AUDITORIA INTERNA">UNIDAD DE AUDITORIA INTERNA</option><option value="UNIDAD DE COMUNICACION SOCIAL">UNIDAD DE COMUNICACION SOCIAL</option><option value="UNIDAD DE GESTION DE PERSONAL DEL SEP">UNIDAD DE GESTION DE PERSONAL DEL SEP</option><option value="UNIDAD DE GESTION JURIDICA">UNIDAD DE GESTION JURIDICA</option><option value="UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO">UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO</option><option value="UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL">UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL</option><option value="UNIDAD DE TITULOS PROFESIONALES">UNIDAD DE TITULOS PROFESIONALES</option><option value="UNIDAD DE TRANSPARENCIA">UNIDAD DE TRANSPARENCIA</option><option value="UNIDAD DE UNIVERSIDADES ">UNIDAD DE UNIVERSIDADES </option><option value="UNIDAD FINANCIERA">UNIDAD FINANCIERA</option><option value="VICEMINISTERIO DE CIENCIA Y TECNOLOGIA">VICEMINISTERIO DE CIENCIA Y TECNOLOGIA</option><option value="VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL">VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL</option><option value="VICEMINISTERIO DE EDUCACION REGULAR">VICEMINISTERIO DE EDUCACION REGULAR</option><option value="VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL">VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL</option></select></div><div id="cab"><input name="date_start'+c+'" type="text" id="date_start'+c+'" size="25" maxlength="64" class="datpick"/></div><div id="cab"><input name="date_end'+c+'" type="text" id="date_end'+c+'" size="25" maxlength="64" class="datpick"/></div><div id="espa"></div><div id="cabmid" class="btn1r"><a href="#" onclick="javascript:borrar('+c+');">Borrar Registro</a></div></div>');
$(function() {
		$( ".datpick" ).datepicker({
			changeMonth: true,
			changeYear: true,
			showOn: "button",
			yearRange: '-100:+0',
			buttonImage: "data/images/calendar.gif",
			buttonImageOnly: true
		});
	});	


}
function borrar(cual) {
	$("div.email"+cual).remove();
	return false;
}

</script>
<script>
function probar(){
if (!(confirm('¿Esta seguro de GUARDAR esta información? \n\rHaga click en "CANCELAR" si desea revisar sus datos, si está seguro del contenido de la información que esta enviando haga click en "ACEPTAR"'))){ 
       return false; 
	   
	   } 
}
</script>
</head>

<body id="bd">

<div id="campos" style="margin-left:70px;">
<img src="data/images/mov.jpg" width="1032" height="50" />
<form id="form1" name="form1" method="post" action="">
  <div id="campos1" class="campos" >
  <!-- TABLA A REPETIR-->
  		<div id="cab">CARGO EN LA INSTITUCION <br>(EMPEZAR POR EL ACTUAL):</div>
  		<div id="cab">MOTIVO DEL CAMBIO DEL CARGO:</div>
  		<div id="cab">NÚMERO DE RESOLUCIÓN O MEMO:    	</div>
		<div id="cab">DIRECCIÓN GENERAL:</div>
		<div id="cab">
  			<input name="charge" type="text" id="charge" size="35" maxlength="64" class="required" />
   		</div>
  		<div id="cab">
  		  <select name="rea_chan" id="rea_chan" >
  		    <option value="PROMOCION">PROMOCIÓN</option>
  		    <option value="RETIRO">RETIRO</option>
  		    <option value="ROTACION">ROTACIÓN</option>
  		    <option value="TRANFERENCIA">TRANFERENCIA</option>
  		    <option value="RENUNCIA">RENUNCIA</option>
  		    <option value="COMISION">COMISION</option>
  		    <option value="-">-</option>
          </select>
  		</div>
  		<div id="cab">
  			<input name="num_res" type="text" id="num_res" size="30" maxlength="64" class="required"/>
   		</div>
  		<div id="cab">
        <select name="gral_dir" id="gral_dir" style="width:200px">
		<option value="ACCESO Y PERMANENCIA (INFRAESTRUCTURA)">ACCESO Y PERMANENCIA (INFRAESTRUCTURA)</option>
		<option value="APACITACION Y EVALUACION DEL DESEMPEÑO">CAPACITACION Y EVALUACION DEL DESEMPEÑO</option>
		<option value="COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION">COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION</option>
		<option value="CORRESPONDENCIA DESPACHO">CORRESPONDENCIA DESPACHO</option>
		<option value="CORRESPONDENCIA EXTERNO SALIENTE">CORRESPONDENCIA EXTERNO SALIENTE</option>
		<option value="DESPACHO DE EDUCACION">DESPACHO DE EDUCACION</option>
		<option value="DESPACHO MINISTRO MEMORANDO">DESPACHO MINISTRO MEMORANDO</option>
		<option value="DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS">DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS</option>
		<option value="DIRECCION GENERAL DE ASUNTOS JURIDICOS">DIRECCION GENERAL DE ASUNTOS JURIDICOS</option>
		<option value="DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA">DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION DE ADULTOS">DIRECCION GENERAL DE EDUCACION DE ADULTOS</option>
		<option value="DIRECCION GENERAL DE EDUCACION ESPECIAL">DIRECCION GENERAL DE EDUCACION ESPECIAL</option>
		<option value="DIRECCION GENERAL DE EDUCACION PRIMARIA">DIRECCION GENERAL DE EDUCACION PRIMARIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SECUNDARIA">DIRECCION GENERAL DE EDUCACION SECUNDARIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA">DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA">DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA</option>
		<option value="DIRECCION GENERAL DE FORMACION DE MAESTROS">DIRECCION GENERAL DE FORMACION DE MAESTROS</option>
		<option value="DIRECCION GENERAL DE PLANIFICACION">DIRECCION GENERAL DE PLANIFICACION</option>
		<option value="DIRECCION GENERAL DE POST ALFABETIZACION">DIRECCION GENERAL DE POST ALFABETIZACION</option>
		<option value="DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION">DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION</option>
		<option value="EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL">EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL</option>
		<option value="EQUIPO BONO JUANCITO PINTO">EQUIPO BONO JUANCITO PINTO</option>
		<option value="EQUIPO DE  AUDITORIA II">EQUIPO DE AUDITORIA II</option>
		<option value="EQUIPO DE ACREDITACION UNIVERSITARIA">EQUIPO DE ACREDITACION UNIVERSITARIA</option>
	<option value="EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES">EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES</option>
		<option value="EQUIPO DE ADMINISTRACION DE PLANILLAS">EQUIPO DE ADMINISTRACION DE PLANILLAS</option>
		<option value="EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO">EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO</option>
		<option value="EQUIPO DE AUDITORIA I">EQUIPO DE AUDITORIA I</option>
		<option value="EQUIPO DE BIENESTAR SOCIAL">EQUIPO DE BIENESTAR SOCIAL</option>
		<option value="EQUIPO DE CONTABILIDAD">EQUIPO DE CONTABILIDAD</option>
		<option value="EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS">EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS</option>
		<option value="EQUIPO DE DESARROLLO ORGANIZACIONAL">EQUIPO DE DESARROLLO ORGANIZACIONAL</option>
		<option value="EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS">EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS</option>
		<option value="EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS">EQUIPO DE DOTACION DE PERSONAl Y PLANILLAS</option>
		<option value="EQUIPO DE EDUCACION ESPECIAL ">EQUIPO DE EDUCACION ESPECIAL </option>
		<option value="EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA">EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA</option>
		<option value="EQUIPO DE FORMACION ARTISTICA">EQUIPO DE FORMACION ARTISTICA</option>
		<option value="EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)">EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)</option>
		<option value="EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL">EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL</option>
		<option value="EQUIPO DE FORMACION INICIAL">EQUIPO DE FORMACION INICIAL</option>
		<option value="EQUIPO DE GENERO GENERACIONAL Y SOCIAL">EQUIPO DE GENERO GENERACIONAL Y SOCIAL</option>
		<option value="EQUIPO DE GESTION CURRICULAR">EQUIPO DE GESTION CURRICULAR</option>
		<option value="EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL">EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL</option>
		<option value="EQUIPO DE GESTION INSTITUCIONAL DGEA">EQUIPO DE GESTION INSTITUCIONAL DGEA</option>
		<option value="EQUIPO DE GESTION INSTITUCIONAL SEP">EQUIPO DE GESTION INSTITUCIONAL SEP</option>
		<option value="EQUIPO DE GESTION Y DESARROLLO CURRICULAR">EQUIPO DE GESTION Y DESARROLLO CURRICULAR</option>
		<option value="EQUIPO DE INFORMACION EDUCATIVA">EQUIPO DE INFORMACION EDUCATIVA</option>
		<option value="EQUIPO DE INFRAESTRUCTURA">EQUIPO DE INFRAESTRUCTURA</option>
		<option value="EQUIPO DE MEMORIA INSTITUCIONAL">EQUIPO DE MEMORIA INSTITUCIONAL</option>
		<option value="EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS">EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS</option>
		<option value="EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO">EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO</option>
		<option value="EQUIPO DE PRESUPUESTOS">EQUIPO DE PRESUPUESTOS</option>
		<option value="EQUIPO DE RELACIONES INTERNACIONALES">EQUIPO DE RELACIONES INTERNACIONALES</option>
		<option value="EQUIPO DE SISTEMAS Y PROCESO DE DATOS">EQUIPO DE SISTEMAS Y PROCESO DE DATOS</option>
		<option value="EQUIPO DE TESORERIA">EQUIPO DE TESORERIA</option>
		<option value="EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)">EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)</option>
		<option value="EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE ">EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE </option>
		<option value="EQUIPO GESTION CURRICULAR INICIAL">EQUIPO GESTION CURRICULAR INICIAL</option>
		<option value="EQUIPO GESTION CURRICULAR PRIMARIA">EQUIPO GESTION CURRICULAR PRIMARIA</option>
		<option value="EQUIPO REGISTRO DOCENTE ADMINISTRATIVO">EQUIPO REGISTRO DOCENTE ADMINISTRATIVO</option>
		<option value="EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC">EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC</option>
		<option value="FORMACION Y CAPACITACION">FORMACION Y CAPACITACION</option>
		<option value="35" title="INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES">INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES</option>
		<option value="JEFATURA DE GABINETE">JEFATURA DE GABINETE</option>
		<option value="OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA">OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA</option>
		<option value="PORTAL EDUCATIVO">PORTAL EDUCATIVO</option>
		<option value="PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)">PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)</option>
		<option value="REGISTRO Y CONTROL DE PERSONAL">REGISTRO Y CONTROL DE PERSONAL</option>
		<option value="SOPORTE TECNICO A USUARIOS">SOPORTE TECNICO A USUARIOS</option>
		<option value="TELECENTROS EDUCATIVOS COMUNITARIO">TELECENTROS EDUCATIVOS COMUNITARIO</option>
		<option value="UNIDAD ADMINISTRATIVA">UNIDAD ADMINISTRATIVA</option>
		<option value="UNIDAD DE ANALISIS JURIDICO">UNIDAD DE ANALISIS JURIDICO</option>
		<option value="UNIDAD DE AUDITORIA INTERNA">UNIDAD DE AUDITORIA INTERNA</option>
		<option value="UNIDAD DE COMUNICACION SOCIAL">UNIDAD DE COMUNICACION SOCIAL</option>
		<option value="UNIDAD DE GESTION DE PERSONAL DEL SEP">UNIDAD DE GESTION DE PERSONAL DEL SEP</option>
		<option value="UNIDAD DE GESTION JURIDICA">UNIDAD DE GESTION JURIDICA</option>
		<option value="UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO">UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO</option>
		<option value="UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL">UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL</option>
		<option value="UNIDAD DE TITULOS PROFESIONALES">UNIDAD DE TITULOS PROFESIONALES</option>
		<option value="UNIDAD DE TRANSPARENCIA">UNIDAD DE TRANSPARENCIA</option>
		<option value="UNIDAD DE UNIVERSIDADES ">UNIDAD DE UNIVERSIDADES </option>
		<option value="UNIDAD FINANCIERA">UNIDAD FINANCIERA</option>
		<option value="VICEMINISTERIO DE CIENCIA Y TECNOLOGIA">VICEMINISTERIO DE CIENCIA Y TECNOLOGIA</option>
		<option value="VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL">VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL</option>
		<option value="VICEMINISTERIO DE EDUCACION REGULAR">VICEMINISTERIO DE EDUCACION REGULAR</option>
		<option value="VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL">VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL</option>
		<option value="OTRO">OTRO</option>
        </select> 
 		</div>
		<div id="cab">UNIDAD:</div>
  		<div id="cab">ÁREA:</div>
    	<div id="cab">DE FECHA:</div>
    	<div id="cab">A FECHA:</div>
 		<div id="cab">
 		<select name="unit" id="unit" style="width:200px">
		<option value="ACCESO Y PERMANENCIA (INFRAESTRUCTURA)">ACCESO Y PERMANENCIA (INFRAESTRUCTURA)</option>
		<option value="APACITACION Y EVALUACION DEL DESEMPEÑO">CAPACITACION Y EVALUACION DEL DESEMPEÑO</option>
		<option value="COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION">COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION</option>
		<option value="CORRESPONDENCIA DESPACHO">CORRESPONDENCIA DESPACHO</option>
		<option value="CORRESPONDENCIA EXTERNO SALIENTE">CORRESPONDENCIA EXTERNO SALIENTE</option>
		<option value="DESPACHO DE EDUCACION">DESPACHO DE EDUCACION</option>
		<option value="DESPACHO MINISTRO MEMORANDO">DESPACHO MINISTRO MEMORANDO</option>
		<option value="DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS">DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS</option>
		<option value="DIRECCION GENERAL DE ASUNTOS JURIDICOS">DIRECCION GENERAL DE ASUNTOS JURIDICOS</option>
		<option value="DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA">DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION DE ADULTOS">DIRECCION GENERAL DE EDUCACION DE ADULTOS</option>
		<option value="DIRECCION GENERAL DE EDUCACION ESPECIAL">DIRECCION GENERAL DE EDUCACION ESPECIAL</option>
		<option value="DIRECCION GENERAL DE EDUCACION PRIMARIA">DIRECCION GENERAL DE EDUCACION PRIMARIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SECUNDARIA">DIRECCION GENERAL DE EDUCACION SECUNDARIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA">DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA">DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA</option>
		<option value="DIRECCION GENERAL DE FORMACION DE MAESTROS">DIRECCION GENERAL DE FORMACION DE MAESTROS</option>
		<option value="DIRECCION GENERAL DE PLANIFICACION">DIRECCION GENERAL DE PLANIFICACION</option>
		<option value="DIRECCION GENERAL DE POST ALFABETIZACION">DIRECCION GENERAL DE POST ALFABETIZACION</option>
		<option value="DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION">DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION</option>
		<option value="EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL">EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL</option>
		<option value="EQUIPO BONO JUANCITO PINTO">EQUIPO BONO JUANCITO PINTO</option>
		<option value="EQUIPO DE  AUDITORIA II">EQUIPO DE AUDITORIA II</option>
		<option value="EQUIPO DE ACREDITACION UNIVERSITARIA">EQUIPO DE ACREDITACION UNIVERSITARIA</option>
	<option value="EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES">EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES</option>
		<option value="EQUIPO DE ADMINISTRACION DE PLANILLAS">EQUIPO DE ADMINISTRACION DE PLANILLAS</option>
		<option value="EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO">EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO</option>
		<option value="EQUIPO DE AUDITORIA I">EQUIPO DE AUDITORIA I</option>
		<option value="EQUIPO DE BIENESTAR SOCIAL">EQUIPO DE BIENESTAR SOCIAL</option>
		<option value="EQUIPO DE CONTABILIDAD">EQUIPO DE CONTABILIDAD</option>
		<option value="EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS">EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS</option>
		<option value="EQUIPO DE DESARROLLO ORGANIZACIONAL">EQUIPO DE DESARROLLO ORGANIZACIONAL</option>
		<option value="EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS">EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS</option>
		<option value="EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS">EQUIPO DE DOTACION DE PERSONAl Y PLANILLAS</option>
		<option value="EQUIPO DE EDUCACION ESPECIAL ">EQUIPO DE EDUCACION ESPECIAL </option>
		<option value="EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA">EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA</option>
		<option value="EQUIPO DE FORMACION ARTISTICA">EQUIPO DE FORMACION ARTISTICA</option>
		<option value="EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)">EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)</option>
		<option value="EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL">EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL</option>
		<option value="EQUIPO DE FORMACION INICIAL">EQUIPO DE FORMACION INICIAL</option>
		<option value="EQUIPO DE GENERO GENERACIONAL Y SOCIAL">EQUIPO DE GENERO GENERACIONAL Y SOCIAL</option>
		<option value="EQUIPO DE GESTION CURRICULAR">EQUIPO DE GESTION CURRICULAR</option>
		<option value="EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL">EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL</option>
		<option value="EQUIPO DE GESTION INSTITUCIONAL DGEA">EQUIPO DE GESTION INSTITUCIONAL DGEA</option>
		<option value="EQUIPO DE GESTION INSTITUCIONAL SEP">EQUIPO DE GESTION INSTITUCIONAL SEP</option>
		<option value="EQUIPO DE GESTION Y DESARROLLO CURRICULAR">EQUIPO DE GESTION Y DESARROLLO CURRICULAR</option>
		<option value="EQUIPO DE INFORMACION EDUCATIVA">EQUIPO DE INFORMACION EDUCATIVA</option>
		<option value="EQUIPO DE INFRAESTRUCTURA">EQUIPO DE INFRAESTRUCTURA</option>
		<option value="EQUIPO DE MEMORIA INSTITUCIONAL">EQUIPO DE MEMORIA INSTITUCIONAL</option>
		<option value="EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS">EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS</option>
		<option value="EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO">EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO</option>
		<option value="EQUIPO DE PRESUPUESTOS">EQUIPO DE PRESUPUESTOS</option>
		<option value="EQUIPO DE RELACIONES INTERNACIONALES">EQUIPO DE RELACIONES INTERNACIONALES</option>
		<option value="EQUIPO DE SISTEMAS Y PROCESO DE DATOS">EQUIPO DE SISTEMAS Y PROCESO DE DATOS</option>
		<option value="EQUIPO DE TESORERIA">EQUIPO DE TESORERIA</option>
		<option value="EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)">EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)</option>
		<option value="EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE ">EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE </option>
		<option value="EQUIPO GESTION CURRICULAR INICIAL">EQUIPO GESTION CURRICULAR INICIAL</option>
		<option value="EQUIPO GESTION CURRICULAR PRIMARIA">EQUIPO GESTION CURRICULAR PRIMARIA</option>
		<option value="EQUIPO REGISTRO DOCENTE ADMINISTRATIVO">EQUIPO REGISTRO DOCENTE ADMINISTRATIVO</option>
		<option value="EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC">EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC</option>
		<option value="FORMACION Y CAPACITACION">FORMACION Y CAPACITACION</option>
		<option value="35" title="INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES">INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES</option>
		<option value="JEFATURA DE GABINETE">JEFATURA DE GABINETE</option>
		<option value="OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA">OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA</option>
		<option value="PORTAL EDUCATIVO">PORTAL EDUCATIVO</option>
		<option value="PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)">PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)</option>
		<option value="REGISTRO Y CONTROL DE PERSONAL">REGISTRO Y CONTROL DE PERSONAL</option>
		<option value="SOPORTE TECNICO A USUARIOS">SOPORTE TECNICO A USUARIOS</option>
		<option value="TELECENTROS EDUCATIVOS COMUNITARIO">TELECENTROS EDUCATIVOS COMUNITARIO</option>
		<option value="UNIDAD ADMINISTRATIVA">UNIDAD ADMINISTRATIVA</option>
		<option value="UNIDAD DE ANALISIS JURIDICO">UNIDAD DE ANALISIS JURIDICO</option>
		<option value="UNIDAD DE AUDITORIA INTERNA">UNIDAD DE AUDITORIA INTERNA</option>
		<option value="UNIDAD DE COMUNICACION SOCIAL">UNIDAD DE COMUNICACION SOCIAL</option>
		<option value="UNIDAD DE GESTION DE PERSONAL DEL SEP">UNIDAD DE GESTION DE PERSONAL DEL SEP</option>
		<option value="UNIDAD DE GESTION JURIDICA">UNIDAD DE GESTION JURIDICA</option>
		<option value="UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO">UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO</option>
		<option value="UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL">UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL</option>
		<option value="UNIDAD DE TITULOS PROFESIONALES">UNIDAD DE TITULOS PROFESIONALES</option>
		<option value="UNIDAD DE TRANSPARENCIA">UNIDAD DE TRANSPARENCIA</option>
		<option value="UNIDAD DE UNIVERSIDADES ">UNIDAD DE UNIVERSIDADES </option>
		<option value="UNIDAD FINANCIERA">UNIDAD FINANCIERA</option>
		<option value="VICEMINISTERIO DE CIENCIA Y TECNOLOGIA">VICEMINISTERIO DE CIENCIA Y TECNOLOGIA</option>
		<option value="VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL">VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL</option>
		<option value="VICEMINISTERIO DE EDUCACION REGULAR">VICEMINISTERIO DE EDUCACION REGULAR</option>
		<option value="VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL">VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL</option>
		<option value="OTRO">OTRO</option>
        </select>         
 		</div>
        <div id="cab">
   		<select name="area" id="area" style="width:200px">
		<option value="ACCESO Y PERMANENCIA (INFRAESTRUCTURA)">ACCESO Y PERMANENCIA (INFRAESTRUCTURA)</option>
		<option value="APACITACION Y EVALUACION DEL DESEMPEÑO">CAPACITACION Y EVALUACION DEL DESEMPEÑO</option>
		<option value="COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION">COORDINACION PLURINACIONAL PARA EL DESARROLLO DE LENGUAS PARA LA EDUCACION</option>
		<option value="CORRESPONDENCIA DESPACHO">CORRESPONDENCIA DESPACHO</option>
		<option value="CORRESPONDENCIA EXTERNO SALIENTE">CORRESPONDENCIA EXTERNO SALIENTE</option>
		<option value="DESPACHO DE EDUCACION">DESPACHO DE EDUCACION</option>
		<option value="DESPACHO MINISTRO MEMORANDO">DESPACHO MINISTRO MEMORANDO</option>
		<option value="DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS">DIRECCION GENERAL DE ASUNTOS ADMINISTRATIVOS</option>
		<option value="DIRECCION GENERAL DE ASUNTOS JURIDICOS">DIRECCION GENERAL DE ASUNTOS JURIDICOS</option>
		<option value="DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA">DIRECCION GENERAL DE CIENCIA Y TECNOLOGIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION DE ADULTOS">DIRECCION GENERAL DE EDUCACION DE ADULTOS</option>
		<option value="DIRECCION GENERAL DE EDUCACION ESPECIAL">DIRECCION GENERAL DE EDUCACION ESPECIAL</option>
		<option value="DIRECCION GENERAL DE EDUCACION PRIMARIA">DIRECCION GENERAL DE EDUCACION PRIMARIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SECUNDARIA">DIRECCION GENERAL DE EDUCACION SECUNDARIA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA">DIRECCION GENERAL DE EDUCACION SUPERIOR TECNICA, TECNOLOGICA, LINGUISTICA Y ARTISTICA</option>
		<option value="DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA">DIRECCION GENERAL DE EDUCACION SUPERIOR UNIVERSITARIA</option>
		<option value="DIRECCION GENERAL DE FORMACION DE MAESTROS">DIRECCION GENERAL DE FORMACION DE MAESTROS</option>
		<option value="DIRECCION GENERAL DE PLANIFICACION">DIRECCION GENERAL DE PLANIFICACION</option>
		<option value="DIRECCION GENERAL DE POST ALFABETIZACION">DIRECCION GENERAL DE POST ALFABETIZACION</option>
		<option value="DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION">DIRECCION GENERAL DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION</option>
		<option value="EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL">EQUIPO ARMONIA CON LA NATURALEZA Y JUSTICIA SOCIAL</option>
		<option value="EQUIPO BONO JUANCITO PINTO">EQUIPO BONO JUANCITO PINTO</option>
		<option value="EQUIPO DE  AUDITORIA II">EQUIPO DE AUDITORIA II</option>
		<option value="EQUIPO DE ACREDITACION UNIVERSITARIA">EQUIPO DE ACREDITACION UNIVERSITARIA</option>
	<option value="EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES">EQUIPO DE ADMINISTRACION DE BIENES Y SERVICIOS GENERALES</option>
		<option value="EQUIPO DE ADMINISTRACION DE PLANILLAS">EQUIPO DE ADMINISTRACION DE PLANILLAS</option>
		<option value="EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO">EQUIPO DE ANALISIS E INVESTIGACION SECTORIAL INDICADORES Y ANALISIS EDUCATIVO</option>
		<option value="EQUIPO DE AUDITORIA I">EQUIPO DE AUDITORIA I</option>
		<option value="EQUIPO DE BIENESTAR SOCIAL">EQUIPO DE BIENESTAR SOCIAL</option>
		<option value="EQUIPO DE CONTABILIDAD">EQUIPO DE CONTABILIDAD</option>
		<option value="EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS">EQUIPO DE CONTRATACIONES DE BIENES Y SERVICIOS</option>
		<option value="EQUIPO DE DESARROLLO ORGANIZACIONAL">EQUIPO DE DESARROLLO ORGANIZACIONAL</option>
		<option value="EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS">EQUIPO DE DISTRIBUCION DE BIENES EDUCATIVOS</option>
		<option value="EQUIPO DE DOTACION  DE PERSONAl Y PLANILLAS">EQUIPO DE DOTACION DE PERSONAl Y PLANILLAS</option>
		<option value="EQUIPO DE EDUCACION ESPECIAL ">EQUIPO DE EDUCACION ESPECIAL </option>
		<option value="EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA">EQUIPO DE EVALUACION CURRICULAR ACADEMICA E INFRAESTRUCTURA</option>
		<option value="EQUIPO DE FORMACION ARTISTICA">EQUIPO DE FORMACION ARTISTICA</option>
		<option value="EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)">EQUIPO DE FORMACION BASICA (GESTION INSTITUCIONAL)</option>
		<option value="EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL">EQUIPO DE FORMACION CONTINUA Y POSTGRADUAL</option>
		<option value="EQUIPO DE FORMACION INICIAL">EQUIPO DE FORMACION INICIAL</option>
		<option value="EQUIPO DE GENERO GENERACIONAL Y SOCIAL">EQUIPO DE GENERO GENERACIONAL Y SOCIAL</option>
		<option value="EQUIPO DE GESTION CURRICULAR">EQUIPO DE GESTION CURRICULAR</option>
		<option value="EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL">EQUIPO DE GESTION DOCENTE Y DESARROLLO INSTITUCIONAL</option>
		<option value="EQUIPO DE GESTION INSTITUCIONAL DGEA">EQUIPO DE GESTION INSTITUCIONAL DGEA</option>
		<option value="EQUIPO DE GESTION INSTITUCIONAL SEP">EQUIPO DE GESTION INSTITUCIONAL SEP</option>
		<option value="EQUIPO DE GESTION Y DESARROLLO CURRICULAR">EQUIPO DE GESTION Y DESARROLLO CURRICULAR</option>
		<option value="EQUIPO DE INFORMACION EDUCATIVA">EQUIPO DE INFORMACION EDUCATIVA</option>
		<option value="EQUIPO DE INFRAESTRUCTURA">EQUIPO DE INFRAESTRUCTURA</option>
		<option value="EQUIPO DE MEMORIA INSTITUCIONAL">EQUIPO DE MEMORIA INSTITUCIONAL</option>
		<option value="EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS">EQUIPO DE NUEVAS TECNOLOGIAS DE INFORMACION Y COMUNICACION NTICS</option>
		<option value="EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO">EQUIPO DE PLANIFICACION OPERATIVA Y SEGUIMIENTO</option>
		<option value="EQUIPO DE PRESUPUESTOS">EQUIPO DE PRESUPUESTOS</option>
		<option value="EQUIPO DE RELACIONES INTERNACIONALES">EQUIPO DE RELACIONES INTERNACIONALES</option>
		<option value="EQUIPO DE SISTEMAS Y PROCESO DE DATOS">EQUIPO DE SISTEMAS Y PROCESO DE DATOS</option>
		<option value="EQUIPO DE TESORERIA">EQUIPO DE TESORERIA</option>
		<option value="EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)">EQUIPO DE UNIVERSIDADES INDIGENAS BOLIVIANAS (UNIBOL)</option>
		<option value="EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE ">EQUIPO EDUCACION INTRA INTERCULTURALIDAD PLURILINGUE </option>
		<option value="EQUIPO GESTION CURRICULAR INICIAL">EQUIPO GESTION CURRICULAR INICIAL</option>
		<option value="EQUIPO GESTION CURRICULAR PRIMARIA">EQUIPO GESTION CURRICULAR PRIMARIA</option>
		<option value="EQUIPO REGISTRO DOCENTE ADMINISTRATIVO">EQUIPO REGISTRO DOCENTE ADMINISTRATIVO</option>
		<option value="EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC">EQUIPO SISTEMA PLURINACIONAL DE CERTIFICACION DE COMPETENCIAS SPCC</option>
		<option value="FORMACION Y CAPACITACION">FORMACION Y CAPACITACION</option>
		<option value="35" title="INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES">INSTITUTO DE INVESTIGACIONES PEDAGOGICAS PLURINACIONALES</option>
		<option value="JEFATURA DE GABINETE">JEFATURA DE GABINETE</option>
		<option value="OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA">OBSERVATORIO PLURINACIONAL DE LA CALIDAD EDUCATIVA</option>
		<option value="PORTAL EDUCATIVO">PORTAL EDUCATIVO</option>
		<option value="PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)">PROYECTOS EDUCATIVOS (PROME-INFRAESTRUCTURA)</option>
		<option value="REGISTRO Y CONTROL DE PERSONAL">REGISTRO Y CONTROL DE PERSONAL</option>
		<option value="SOPORTE TECNICO A USUARIOS">SOPORTE TECNICO A USUARIOS</option>
		<option value="TELECENTROS EDUCATIVOS COMUNITARIO">TELECENTROS EDUCATIVOS COMUNITARIO</option>
		<option value="UNIDAD ADMINISTRATIVA">UNIDAD ADMINISTRATIVA</option>
		<option value="UNIDAD DE ANALISIS JURIDICO">UNIDAD DE ANALISIS JURIDICO</option>
		<option value="UNIDAD DE AUDITORIA INTERNA">UNIDAD DE AUDITORIA INTERNA</option>
		<option value="UNIDAD DE COMUNICACION SOCIAL">UNIDAD DE COMUNICACION SOCIAL</option>
		<option value="UNIDAD DE GESTION DE PERSONAL DEL SEP">UNIDAD DE GESTION DE PERSONAL DEL SEP</option>
		<option value="UNIDAD DE GESTION JURIDICA">UNIDAD DE GESTION JURIDICA</option>
		<option value="UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO">UNIDAD DE POLITICAS DE INTRACULTURALIDAD, INTERCULTURALIDAD Y PLURILINGUISMO</option>
		<option value="UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL">UNIDAD DE RRHH Y DESARROLLO ORGANIZACIONAL</option>
		<option value="UNIDAD DE TITULOS PROFESIONALES">UNIDAD DE TITULOS PROFESIONALES</option>
		<option value="UNIDAD DE TRANSPARENCIA">UNIDAD DE TRANSPARENCIA</option>
		<option value="UNIDAD DE UNIVERSIDADES ">UNIDAD DE UNIVERSIDADES </option>
		<option value="UNIDAD FINANCIERA">UNIDAD FINANCIERA</option>
		<option value="VICEMINISTERIO DE CIENCIA Y TECNOLOGIA">VICEMINISTERIO DE CIENCIA Y TECNOLOGIA</option>
		<option value="VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL">VICEMINISTERIO DE EDUCACION ALTERNATIVA Y ESPECIAL</option>
		<option value="VICEMINISTERIO DE EDUCACION REGULAR">VICEMINISTERIO DE EDUCACION REGULAR</option>
		<option value="VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL">VICEMINISTERIO DE EDUCACION SUPERIOR DE FORMACION PROFESIONAL</option>
		<option value="OTRO">OTRO</option>
        </select>   
          
          
          
          
          
        </div>
  		<div id="cab">
  		  <input name="date_start" type="text" id="date_start" size="25" maxlength="64" class="datpick"/>
		</div>
  		<div id="cab">
  		  <input name="date_end" type="text" id="date_end" size="25" maxlength="64" class="datpick"/>
		</div>
		<div id="espa"></div>
  		<div id="cabmid" class="btn1"><a href="javascript:agregar();">Agregar Registro</a></div>
 		<input type="submit" class="submit" onclick="return probar()" name="save" id="loginbutton" value="Guardar" />
<!-- FIN -->
</div>
</form>
</body>
</html>